name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with Python
      run: |
        pyinstaller --onefile --name=course_scheduler --icon=res/icon.ico --add-data "res/icon.png;." --clean --noconfirm --noconsole main.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: dist/

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: executables
        path: dist/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: ${{ github.ref_name }}
        generate_release_notes: true
        files: |
          dist/course_scheduler.exe
