name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build 64-bit with Python
      run: |
        pyinstaller --onefile --name=app_64_py --icon=icon.ico --clean --noconfirm main.py

    - name: Build 32-bit with Python
      run: |
        set PYTHONARCH=32
        pyinstaller --onefile --name=app_32_py --icon=icon.ico --clean --noconfirm main.py

    - name: Build 64-bit without Python
      run: |
        pyinstaller --onefile --name=app_64_nopy --icon=icon.ico --clean --noconfirm --noconsole main.py

    - name: Build 32-bit without Python
      run: |
        set PYTHONARCH=32
        pyinstaller --onefile --name=app_32_nopy --icon=icon.ico --clean --noconfirm --noconsole main.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executables
        path: dist/

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: executables
        path: dist/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        generate_release_notes: true
        files: |
          dist/app_64_py.exe
          dist/app_32_py.exe
          dist/app_64_nopy.exe
          dist/app_32_nopy.exe
